# Generated by Django 4.2.13 on 2024-07-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iihmrapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trn_tbl_hh_consent_form',
        ),
    ]
