# Generated by Django 4.2.13 on 2024-07-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iihmrapp', '0002_delete_trn_tbl_hh_consent_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trn_tbl_hh_consent_form',
            fields=[
                ('fld_slno', models.AutoField(primary_key=True, serialize=False)),
                ('fld_rn', models.IntegerField(db_index=True)),
                ('fld_rf_id', models.IntegerField(db_index=True)),
                ('fld_user_swid', models.CharField(max_length=50, null=True)),
                ('fld_user_name', models.CharField(max_length=100, null=True)),
                ('fld_state_swid', models.CharField(max_length=100, null=True)),
                ('fld_state_code', models.CharField(max_length=100, null=True)),
                ('fld_state_name', models.CharField(max_length=100, null=True)),
                ('fld_district_swid', models.CharField(max_length=100, null=True)),
                ('fld_district_code', models.CharField(max_length=100, null=True)),
                ('fld_district_name', models.CharField(max_length=100, null=True)),
                ('fld_taluk_swid', models.CharField(max_length=100, null=True)),
                ('fld_taluk_code', models.CharField(max_length=100, null=True)),
                ('fld_taluk_name', models.CharField(max_length=100, null=True)),
                ('fld_block_sw_Id', models.CharField(max_length=100, null=True)),
                ('fld_block_code', models.CharField(max_length=100, null=True)),
                ('fld_block_name', models.CharField(max_length=100, null=True)),
                ('fld_panchyt_swid', models.CharField(max_length=100, null=True)),
                ('fld_panchyt_code', models.CharField(max_length=100, null=True)),
                ('fld_panchyt_name', models.CharField(max_length=100, null=True)),
                ('fld_phc_swid', models.CharField(max_length=100, null=True)),
                ('fld_phc_code', models.CharField(max_length=100, null=True)),
                ('fld_phc_name', models.CharField(max_length=100, null=True)),
                ('fld_hsc_hwc_swid', models.CharField(max_length=100, null=True)),
                ('fld_hsc_hwc_code', models.CharField(max_length=100, null=True)),
                ('fld_hsc_hwc_name', models.CharField(max_length=100, null=True)),
                ('fld_village_swid', models.CharField(max_length=100, null=True)),
                ('fld_village_code', models.CharField(max_length=100, null=True)),
                ('fld_village_name', models.CharField(max_length=100, null=True)),
                ('fld_hh_number', models.CharField(max_length=100, null=True)),
                ('fld_respondent_name', models.CharField(max_length=100, null=True)),
                ('fld_hh_id', models.CharField(max_length=100, null=True)),
                ('fld_agreed_paricipate_survy_id', models.CharField(max_length=50, null=True)),
                ('fld_agreed_paricipate_survy_name', models.CharField(max_length=100, null=True)),
                ('fld_date_of_interview', models.CharField(max_length=100, null=True)),
                ('fld_is_active', models.CharField(db_index=True, max_length=2)),
                ('fld_system_inserted_datetime', models.CharField(max_length=50)),
                ('fld_modified_no', models.IntegerField(null=True)),
                ('fld_modified_datetime', models.CharField(max_length=50, null=True)),
                ('fld_is_deleted', models.CharField(db_index=True, max_length=2, null=True)),
                ('fld_reason_for_deletion', models.TextField(null=True)),
                ('fld_is_deleted_datetime', models.CharField(max_length=100, null=True)),
                ('fld_sent_to_server', models.CharField(db_index=True, default=0, max_length=2, null=True)),
                ('fld_qid', models.CharField(db_index=True, max_length=100, null=True)),
                ('fld_data_source', models.CharField(max_length=50, null=True)),
                ('fld_loggedin_user_id', models.CharField(max_length=100, null=True)),
                ('fld_form_start_time', models.CharField(max_length=50)),
                ('fld_form_end_time', models.CharField(max_length=50)),
                ('fld_is_full_form_completed_form', models.CharField(max_length=20)),
                ('fld_app_version', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'trn_tbl_hh_consent_form',
            },
        ),
    ]
